### ISSUE TITLE
Content in the main project is broken

### ISSUE THREAD

**Issue by Exerionius** [Synammon/MG-EyesOfTheDragon#1]
If you clone the repo and try to build it, it will fail on a content building stage.

To fix that you need to perform the following steps:
1. Open `Game/Classes/Fighter.xml` file
2. Manually add `<level>1</level>` node between the `EntityName` and the `Strength` nodes
3. Manually add the following nodes after the the `MagicFormula` node:
   `<MaximumHealth>100</MaximumHealth>`
  `<MaximumStamina>100</MaximumStamina>`
  `<MaximumMana>100</MaximumMana>`
5. Repeat steps 1-3 for the `Rogue.xml`, `Priest.xml`, `Wizard.xml`
4. Open main project's content in MGCB and remove a dead link to the whole folder ../../../gamedata14/
5. Rebuild the content

After that the whole project should build without problems.

I can only assume that this broken state of the project is a result of not very successful migration of the series from XNA to Monogame.

Best regards

**Comment by Synammon** [comment]
There was a break in tutorial 39 because of a code change that was not picked up when building the project. It has been resolved in tutorial 40 and is now part of the latest commit.

**Comment by Exerionius** [comment]
Can confirm, it works now. But the reference to the gamedata14 folder up several levels in hierarchy still looks very weird.

Thanks!
